"""Minimal EPUB binder working directly on in-memory ``Novel`` objects.

No database, no artifacts, no translations: just a book and chapter bodies.
"""

import logging
from pathlib import Path
from typing import List, Optional

from ebooklib import epub  # type: ignore

from ..assets.epub import epub_cover_xhtml
from ..core import Chapter, Novel
from ..utils.text_tools import generate_md5

logger = logging.getLogger(__name__)

STYLE = """\
body { font-family: serif; max-width: 40em; margin: auto; padding: 1em; }
h1.chapter-title { font-size: 1.3em; }
p { line-height: 1.6; }
"""

PROJECT_URL = "https://github.com/lncrawl/lightnovel-crawler"


def _chapter_item(chapter: Chapter) -> "epub.EpubHtml":
    body = chapter.body or "<p><em>No content.</em></p>"
    content = f"""\
<div>
  <h4>#{chapter.id}</h4>
  <h1 class="chapter-title">{chapter.title}</h1>
  {body}
</div>
"""
    item = epub.EpubHtml(
        title=chapter.title,
        file_name=f"chapter_{chapter.id:05}.xhtml",
        content=content,
    )
    item.add_link(href="style.css", rel="stylesheet", type="text/css")
    return item


def _intro_item(novel: Novel) -> "epub.EpubHtml":
    content = f"""\
<div>
  <h1>{novel.title}</h1>
  <h3>{novel.author}</h3>
  <div>{novel.synopsis or ""}</div>
  <div><b>Source:</b> <a href="{novel.url}">{novel.url}</a></div>
  <div><i>Generated by Lightnovel Crawler (mini)</i></div>
</div>
"""
    item = epub.EpubHtml(title="Intro", file_name="intro.xhtml", content=content)
    item.add_link(href="style.css", rel="stylesheet", type="text/css")
    return item


def make_epub(
    novel: Novel,
    chapters: List[Chapter],
    out_file: Path,
    cover_file: Optional[Path] = None,
) -> Path:
    book = epub.EpubBook()
    book.set_identifier(generate_md5(novel.url, novel.title)[:40])
    book.set_title(novel.title or "Untitled")
    if novel.author:
        book.add_author(novel.author)
    book.set_language(novel.language or "en")
    for tag in novel.tags or []:
        book.add_metadata("DC", "subject", tag)

    style_item = epub.EpubItem(
        file_name="style.css",
        media_type="text/css",
        content=STYLE.encode(),
    )
    book.add_item(style_item)

    intro = _intro_item(novel)
    book.add_item(intro)

    toc = []
    spine = ["nav", intro]
    for chapter in chapters:
        if not chapter.success:
            continue
        item = _chapter_item(chapter)
        book.add_item(item)
        spine.append(item)
        toc.append(item)

    book.toc = toc
    book.spine = spine

    # The cover page must be added *before* the nav item: when the writer
    # processes the nav it scans every other document (``epub3_pages``), and
    # ``EpubCoverHtml`` only loads its template when it is written itself.
    if cover_file and cover_file.is_file():
        book.set_template("cover", epub_cover_xhtml())
        book.set_cover("cover.jpg", cover_file.read_bytes(), create_page=True)
        book.spine.insert(1, "cover")

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    out_file.parent.mkdir(parents=True, exist_ok=True)
    epub.write_epub(str(out_file), book, {})
    logger.info(f"Created: {out_file}")
    return out_file
